WITH RECURSIVE HOURS AS (
SELECT 0 AS n
    
    UNION ALL
    
    SELECT n+1
    FROM HOURS
    WHERE n<23
)

Select H.n , COUNT(O.DATETIME)
FROM HOURS H
LEFT JOIN ANIMAL_OUTS O
ON H.n = HOUR(O.DATETIME)
GROUP BY H.n
ORDER BY H.n